### ISSUE TITLE
Chat api : Error: Requested entity was not found when trying to list Spaces

### ISSUE THREAD

**Issue by jeromeSH26** [googleapis/google-api-nodejs-client#1940] opened 2020-01-20 20:00 UTC
Hi, I'm trying to list the spaces a user is member of.  When querying, I got this error which I don't get the meaning. Using a service account that has the chat.bot scope available, and passing the user in the "subject" field when requesting the token.  What is the issue then?

```js
const auth = await getGoogleServiceAccountCredentials(
	credentials[0].scopes,
	credentials[0].credentials.client_email,
	credentials[0].credentials.private_key,
	useraccount,  <----user account I want the list of spaces
	credentials[0].credentials.private_key_id,
	undefined
);
const chat = google.chat({ version: "v1", auth });
const chatList = await chat.spaces.list();
console.log(chatList.data.spaces); 
```

**Comment by adamsar** [comment] 2020-08-17 04:28
Same problem here for me:

Simple code to reproduce:

```
const keyFile = process.env["GOOGLE_CHAT_KEYFILE"]
const chatClient = google.chat({
        auth: new GoogleAuth({keyFile, scopes: ["https://www.googleapis.com/auth/chat.bot"]}),
        version: "v1"
    });
chatClient.spaces.list().then(response => console.log(response.data))
```

Key file obtained via instructions on https://developers.google.com/hangouts/chat/how-tos/service-accounts

Note that as per instructions I have not included any roles. this is on a fresh account with a single room in google chat.

**Comment by adamsar** [comment] 2020-08-17 05:23
I'm beginning to think this is an issue with the rest API itself, as I can reproduce this outside the SDK by using the generated token.

**Comment by fhinkel** [comment] 2020-12-07 09:51
Thanks for reporting the issue to the Chat API team. Looks like we can close this.

**Closed by fhinkel** 2020-12-07 09:51 UTC
Labels: api: chat, type: question
