### ISSUE TITLE
Why do I still receive notifications after stop watching a channel?

### ISSUE THREAD

**Issue by sangdth** [googleapis/google-api-nodejs-client#1402] opened 2018-10-22 18:53 UTC
#### Environment details

  - OS: MacOS 10.13.6
  - Node.js version: 8.11.4
  - npm version: 6.4.1
  - `googleapis` version: 27.0.0

#### Steps to reproduce

  1. Create 3 watches with id `...-111`, `...-222`, `...-333`, to watch events change on my "primary" calendar. It works perfectly. I change some events, it will push notitifications.

  2. Stop watch id `...-222`, success.
```
 calendar.channels.stop({
     resource: {
         id: channelId, // channel ID: aasdf-123-fghj-qwer-5467a-222
         resourceId,
    },
  }, (error, result) => {
    if (error) throw error;
    console.log('Close successfully!'); // This successfully printed out
  });
```
  2. Change something on Google Calendar, still receive signal from ID `...-222`:
````
received signal from Google
listen on channel ID:  aasdf-123-fghj-qwer-5467a-222
and resource ID is: R6UYSjrlMC-1EVvMMHNoFKl1jDg
received signal from Google
listen on channel ID:  aasdf-123-fghj-qwer-5467a-111
and resource ID is: R6UYSjrlMC-1EVvMMHNoFKl1jDg
received signal from Google
listen on channel ID:  aasdf-123-fghj-qwer-5467a-333
and resource ID is: R6UYSjrlMC-1EVvMMHNoFKl1jDg
````
You can check the code in here https://github.com/sangdth/dev-api/blob/cf4bd6b30bcaf64b8352a228a8c7d33c05e334a1/google-calendar.js#L144

Does it caused by cache? Or I missed anything?

Thanks in advance.

**Comment by sangdth** [comment] 2018-10-22 20:01
In step 2, if I add `token`, problem seems to be solved.
```
resource: {
    id: channelId, // channel ID: aasdf-123-fghj-qwer-5467a-222
    token: `token-${channelId}`,
    resourceId,
},
```

**Comment by sangdth** [comment] 2018-10-24 15:57
Still have problem, so I reopen this. If I close one channel, and if I close it again with same ID, I get error message that can not find that channel ID, which mean the channel already closed, but I still get notifications from Google API. Can somebody explains?

**Comment by fhinkel** [comment] 2020-12-07 09:27
Hi @sangdth , thank you for the detailed bug report. Unfortunately, this issue tracker has limited visibility and scope - basically, it's just for reporting issues with the samples contained here and is only watched by the folks who work on these samples.

We are happy to help you move this bug to venues where it'll get the attention of the appropriate product teams.

* [StackOverflow's Google Calendar tag](https://stackoverflow.com/questions/tagged/google-calendar-api) is most appropriate for design and general troubleshooting.
* [Google Calendar's public issue tracker](https://b.corp.google.com/issues?q=status:open%20componentid:191627%2B%20type:bug) is most appropriate for bugs and unexpected behavior.
* [Google Calendar Support](https://support.google.com/calendar)

I'm going to close this issue because the folks who own this repo have no actionable way to resolve it directly, but please let us know if there's anything we can do to help!

**Closed by fhinkel** 2020-12-07 09:27 UTC
Labels: api: calendar, type: question
