### ISSUE TITLE
can't create file inside electron's rendring process

### ISSUE THREAD

**Issue by appfinder** [googleapis/google-api-nodejs-client#2032] opened 2020-04-10 15:30 UTC
Hello Team,

I don 't know if this is related to `google-api-nodejs-client` or `electron`
but I've been trying to use the api to create a google drive file in an electron api using the code bellow but i got a an error
`GaxiosError: Invalid multipart request with 0 mime parts.
    at Gaxios._request (http://localhost:4200/vendor.js:90110:23)`
after some debugging and research i discovered that the drive.files.create method only work in the electron main process but if i moved the code into the main process the code work fine.

```
drive.files.create({
    resource: {
      name: 'Another File 7',
      mimeType: 'text/plain',
    },
    media: {
      mimeType: 'text/plain',
      body: 'File Body 7',
    }
  }, (err, result) => {
    if (err) {
      log.error(err)
    }
    else {
      log.log(result)
    }
  });
```

**Comment by bcoe** [comment] 2020-04-13 21:18
Hey @appfinder 👋, I'm 95% sure this is a duplicate of #1878, so let's combine our efforts here.

I'm hoping to start digging into this bug shortly.

**Closed by bcoe** 2020-04-13 21:18 UTC
