### ISSUE TITLE
Google meet created from calendar API does auto admit people

### ISSUE THREAD

**Issue by ishan28mkip** [googleapis/google-api-nodejs-client#2347] opened 2020-09-01 23:51 UTC
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

1) Is this a client library issue or a product issue?
Yes it is a client library issue

2) Did someone already solve this?
No solution found on issues / stackoverflow

3) Do you have a support contract?
No

If the support paths suggested above still do not result in a resolution, please provide the following details.

#### Environment details

  - OS: macOS Catalina 10.15.6
  - Node.js version: v12.18.3
  - npm version:6.14.6
  - `googleapis` version: 59

#### Steps to reproduce

1.  Create calendar event with meet using https://developers.google.com/calendar/v3/reference/events API
2. Add attendees and conferenceData.createRequest object to create a new google meet along the calendar event

- Calendar event gets added in guest calendar
- When a guest/attendee logged in his google account goes to the google meet he is not auto admitted and requires ask to join.

1. If a calendar event is created here https://calendar.google.com/calendar/r/eventedit?vcon=meet&dates=now&hl=en-GB and guests are added.

- Calendar event gets added in guest calendar
- When a guest/attendee logged in his google account goes to the google meet he is auto admitted.

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by sofisl** [comment] 2020-09-02 16:59
Hi there! Would you mind sharing your code (without any personal identifying info)? Thank you in advance!

**Comment by s4kh** [comment] 2020-10-06 07:16
Hi @sofisl. Having same issue. Below is my snippet.

```
const requestId = uuidv4();
  const event = {
    summary: googleEvent.summary,
    description: googleEvent.description,
    start: {
      dateTime: moment(googleEvent.startTime).format(),
    },
    end: {
      dateTime: moment(googleEvent.endTime).format(),
    },
    conferenceData: {
      createRequest: {
        conferenceSolutionKey: {
          type: 'hangoutsMeet',
        },
        requestId,
      },
    },
    reminders: {
      useDefault: false,
      overrides: [
        { method: 'popup', minutes: 10 },
        { method: 'email', minutes: 30 },
      ],
    },
    attendees: googleEvent.attendees,
    organizer: {
      email: googleEvent.creator.email,
    },
  };

  const gEvent = await api.events.insert(
    {
      calendarId,
      requestBody: event,
      sendUpdates: 'all',
      conferenceDataVersion: 1,
    },
  );
```

**Comment by fhinkel** [comment] 2020-12-07 10:55
Hi @ishan28mkip , thank you for the detailed bug report. Unfortunately, this issue tracker has limited visibility and scope - basically, it's just for reporting issues with the samples contained here and is only watched by the folks who work on these samples.

We are happy to help you move this bug to venues where it'll get the attention of the appropriate product teams.

* [StackOverflow's Google Calendar tag](https://stackoverflow.com/questions/tagged/google-calendar-api) is most appropriate for design and general troubleshooting.
* [Google Calendar's public issue tracker](https://b.corp.google.com/issues?q=status:open%20componentid:191627%2B%20type:bug) is most appropriate for bugs and unexpected behavior.
* [Google Calendar Support](https://support.google.com/calendar)

I'm going to close this issue because the folks who own this repo have no actionable way to resolve it directly, but please let us know if there's anything we can do to help!

**Closed by fhinkel** 2020-12-07 10:55 UTC
Labels: needs more info, type: question

**Comment by MrXyfir** [comment] 2022-06-30 16:18
Did anyone ever figure this out?
