### ISSUE TITLE
Gmail performance issue getting messages with attachments since v28

### ISSUE THREAD

**Issue by albert-gonzalez** [googleapis/google-api-nodejs-client#1376] opened 2018-10-04 11:57 UTC
Hi!

#### Environment details

  - OS: Ubuntu 18.04.1
  - Node.js version: 8.12.0
  - npm version: 6.2.0
  - `googleapis` version: 34.0.0

#### Steps to reproduce

I am testing the method gmail.users.messages.get, and I think that there is a performance issue since v28. I get a message with a 7MB attachment using this code

```js
gmail.users.messages.get({
        auth: client,
        userId: 'me',
        id: id,
        format: 'raw'
    });
```

With v24 the time is around 3s. The time output of a call is:

```
real    0m2,849s
user    0m0,501s
sys     0m0,052s
```

With v27 the time is around 4s.  Time output:

```
real    0m3,629s
user    0m1,457s
sys     0m0,924s
```

Since v28, the time is around 16-20s. Time output:

```
real    0m15,368s
user    0m10,911s
sys     0m5,026s
```

Can you help me, please? If i am doing something wrong or you need more info, please tell me.

Thank you!

**Comment by albert-gonzalez** [comment] 2018-10-06 11:49
Hi again,

it seems that gzip is causing the big performance issue, if I remove the line:

https://github.com/googleapis/nodejs-googleapis-common/blob/master/src/apirequest.ts#L230

The time is 2-3 seconds slower than v27, but a lot faster than v34. Probably there are other things that make it slower.

Best Regards!

**Comment by grant** [comment] 2018-11-02 21:16
@albert-gonzalez Are you looking to disable gzip in the Gmail API request header?

**Comment by albert-gonzalez** [comment] 2018-11-02 21:48
Hi,

I was trying to figure out what was the performance issue. Then, I found that disabling the gzip the performance improved a lot and I told you because maybe it would help. But I opened the issue because the performance of old versions is a lot better than the new ones. The performance problem started at v27 or v28.

Thank you!

**Comment by remidenele** [comment] 2018-11-28 11:02
Hi,

I also have performance concerns when using `gmail.users.messages.get` and `gmail.users.messages.attachments.get`.

By doing some profiling, I noticed that most of the time consumed comes from a `Buffer.concat` operation in [axios http adapter](https://github.com/axios/axios/blob/v0.18.0/lib/adapters/http.js#L183).

Below are the elapsed times to retieve a 10MB attachment from a Gmail email with different methods:

| using googleapis@34.0.0 | using [request-promise-native](https://github.com/request/request-promise-native) | using googleapis@34.0.0 but commenting lines 183 to 186 in axios@0.18.0 http adapter |
| --- | --- | --- |
| 102141.546ms | 3541.013ms | 4042.996ms

It seems to be related to the introduction of the axios dependency in [googleapis@25.0.0](https://github.com/googleapis/google-api-nodejs-client/releases/tag/v25.0.0) to change the transport used for HTTP requests from request to axios

**Comment by bradvogel** [comment] 2018-12-04 19:33
Bump on this. We're hitting it too!

**Comment by uberism** [comment] 2019-01-18 21:40
> Hi,
> 
> I also have performance concerns when using `gmail.users.messages.get` and `gmail.users.messages.attachments.get`.
> 
> By doing some profiling, I noticed that most of the time consumed comes from a `Buffer.concat` operation in [axios http adapter](https://github.com/axios/axios/blob/v0.18.0/lib/adapters/http.js#L183).
> 
> Below are the elapsed times to retieve a 10MB attachment from a Gmail email with different methods:
> using googleapis@34.0.0 	using [request-promise-native](https://github.com/request/request-promise-native) 	using googleapis@34.0.0 but commenting lines 183 to 186 in axios@0.18.0 http adapter
> 102141.546ms 	3541.013ms 	4042.996ms
> 
> It seems to be related to the introduction of the axios dependency in [googleapis@25.0.0](https://github.com/googleapis/google-api-nodejs-client/releases/tag/v25.0.0) to change the transport used for HTTP requests from request to axios

I can confirm that this is the case as well. I suppose the workaround is to use request-promise-native.

**Comment by JustinBeckwith** [comment] 2019-01-18 22:12
👋 We are actively looking into this by using `node-fetch` under the hood instead of axios.  More coming soon :)

**Comment by albert-gonzalez** [comment] 2019-01-21 07:42
Hi! I have just tested it with an email with an attachment of 13 MB. With master the result is:

```
real    0m7,633s
user    0m2,766s
sys     0m0,908s
```

And with v36 the result is:
```
real    1m58,053s
user    1m41,921s
sys     1m5,620s
```

The performance improvement is really amazing!

Great work and thank you!

**Comment by JustinBeckwith** [comment] 2019-01-21 07:44
SWEET.  I'm going to go ahead and close this out.  If y'all keep running into issues - please do let us know!

**Closed by JustinBeckwith** 2019-01-21 07:44 UTC
Labels: performance, type: feature request

**Comment by bradvogel** [comment] 2019-01-21 18:12
Thanks all! Just to be clear - what google-api-nodejs-client release is this performance regression fixed in? Is the performance back to the baseline measurement before the v28 regression?

**Comment by JustinBeckwith** [comment] 2019-01-21 18:44
This should be in the next release (37), which will come out this week.  It's a very big release (webpack support!) So it'll take a bit of verification.
