### ISSUE TITLE
googleapis and oclif - running tests. Timeouts tests as it takes 5s+ when googleapis lib is imported

### ISSUE THREAD

**Issue by RuslanZavacky** [googleapis/google-api-nodejs-client#1610] opened 2019-02-22 11:56 UTC
#### Environment details

  - OS: Mojave 10.14.3
  - Node.js version: v8.12.0
  - npm version: 6.7.0 (even though I use yarn - 1.12.1)
  - `googleapis` version: ^37.2.0

#### Steps to reproduce

  1. Install oclif & npx (`yarn global add oclif` && `yarn global add npx`)
  2. `npx oclif multi googleapis-test` - create an initial project
![screenshot 2019-02-22 at 11 43 07](https://user-images.githubusercontent.com/103556/53240606-0c8c6580-3697-11e9-815a-cb7389468571.png)
  3. `cd googleapis-test`
  3. `yarn test` - this validates that tests work
  4. `yarn add googleapis`
  5. `yarn test` - this validates that tests still work
  6. Open `src/commands/hello.ts` and add `import {google} from 'googleapis';`
  7. `yarn test` - validate that it takes ~5seconds to load just google from googleapis. If you are lucky and on more powerful machine your first test will load < 5 seconds and it will pass.

This is what I get sometimes on a project:

![screenshot 2019-02-22 at 11 53 04](https://user-images.githubusercontent.com/103556/53241079-76593f00-3698-11e9-972c-ba3f51ce0835.png)

It does look like googleapis load everything at once, instead of being lazy loaded. 

I see that you have issue #806 - but it seems it's a priority in any way :( So opening this issue to raise awareness again as it might cause more frustration to other developers. 

I've spent couple hours chasing ghosts and though that I did something wrong with my testing infrastructure :)

Thanks!

**Comment by grant** [comment] 2019-06-13 20:15
The issue is that it takes 5s to load `{google}`? I think this is more of an issue with the setup described here (maybe using `oclif`) rather than this module.

I use this module for `@google/clasp` and have seen < 2s load speeds for `googleapis`.

Using a bare-bones sample shouldn't take 13s as shown in your screenshot.

Can you provide a smaller sample that doesn't use any other dependencies other than this module?

Closing as this seems like a very user-specific issue and can't be reproduced.

**Closed by grant** 2019-06-13 20:15 UTC
Labels: type: question
