### ISSUE TITLE
@googleapis packages are not being updated in npm

### ISSUE THREAD

**Issue by MarcCelani-at** [googleapis/google-api-nodejs-client#2750] opened 2021-09-17 00:24 UTC
@googleapis apis are all 5-6 months old. Do you intend to keep them up to date with googleapis? I diff'd the build files for some apis we are using and found that there are some subtle differences. Here is an example:

diff node_modules/@googleapis/admin/build/index.js node_modules/googleapis/build/src/apis/admin/index.js
14a15
> exports.admin_reports_v1 = exports.admin_directory_v1 = exports.admin_datatransfer_v1 = exports.auth = exports.admin = exports.VERSIONS = void 0;
18c19
< exports.admin_datatransfer_v1 = datatransfer_v1_1.admin_datatransfer_v1;
---
> Object.defineProperty(exports, "admin_datatransfer_v1", { enumerable: true, get: function () { return datatransfer_v1_1.admin_datatransfer_v1; } });
20c21
< exports.admin_directory_v1 = directory_v1_1.admin_directory_v1;
---
> Object.defineProperty(exports, "admin_directory_v1", { enumerable: true, get: function () { return directory_v1_1.admin_directory_v1; } });
22c23
< exports.admin_reports_v1 = reports_v1_1.admin_reports_v1;
---
> Object.defineProperty(exports, "admin_reports_v1", { enumerable: true, get: function () { return reports_v1_1.admin_reports_v1; } });
35,36c36
< exports.AuthPlus = googleapis_common_2.AuthPlus;
< //# sourceMappingURL=index.js.map
\ No newline at end of file
---
> Object.defineProperty(exports, "AuthPlus", { enumerable: true, get: function () { return googleapis_common_2.AuthPlus; } });

**Comment by MarcCelani-at** [comment] 2021-09-17 00:25
This is comparing @googleapis/admin@^0.3.0 and googleapis@^85.0.0...

**Comment by sofisl** [comment] 2021-09-17 16:39
Hi @MarcCelani-at, 

Thanks so much for this report. You're completely right, it looks like @googleapis/admin is at [v4](https://github.com/googleapis/google-api-nodejs-client/releases/tag/admin-v4.0.0), and npm only has it published at [v0.3.0](https://www.npmjs.com/package/@googleapis/admin). This is a bug, I'lll look into it.

**Comment by bcoe** [comment] 2021-09-20 16:54
This for brining this bug to our attention @MarcCelani-at, the issue that was preventing submodules from publishing has been addressed as of last week, see recent publications of modules like https://www.npmjs.com/package/@googleapis/sqladmin.

Other modules will be released as updates are made. Do you have an explicit need for new features in `@googleapis/admin`, or did you just raise this as an example?

**Comment by MarcCelani-at** [comment] 2021-09-20 17:14
As long as these are released regularly, I can wait for the next update to catch back up, but if you want to be a superhero, we use admin, calendar, drive, gmail, and sheets. From what I can gather, I don't think there are any changes that I'm worried about missing...

**Closed** 2022-03-07 20:39 UTC
Labels: type: bug, priority: p2

**Comment by bcoe** [comment] 2022-03-07 20:40
I have confirmed that publications are working like a charm these days. Please let us know if you continue to bump into issues.
