### ISSUE TITLE
PDF Download issue in server

### ISSUE THREAD

**Issue by sachinsahu731** [googleapis/google-api-nodejs-client#2278] opened 2020-07-13 10:53 UTC
- Product issue

#### Environment details
-    OS: Linux
  - Node.js version: v8.12.0
  - npm version:6.4.1
  - `googleapis` version:^27.0.0

#### Issue Description
We use this module for JPG,PNG,MP4,PDF for downloading the content all mime-type working fine apart from PDF.
The PDF download worked fine when in the local machine(window).But when we tested the same code on server (UNIX) the PDF file was not downloaded fully (complete PDF not downloaded).Its not downloaded in complete bytes.
Local machine -: 99K (bytes)- downloaded in local machine
Server -: 96k(bytes) -downloaded in server -: 

So the complete PDF is not downloaded and when we try to open its throw "Failed to load PDF document." error

#### Steps to reproduce

  1. When we try to Download the  pdf in bulk we got the issue 

### Code  

```js
var dest = fs.createWriteStream(filePath);
drive.files.get({ fileId: fileId, alt: 'media' }, {
  responseType: 'stream'
}, function (err, response) {
  console.log(err);
  if (err) return callback(err);
  response.data.on('error', err => {
    console.log(err);
    callback(err);
  }).on('end', () => {
    logger.info(":::Downloading file from google drive:::===>" + fileName);
    callback(null, fileName);
  }).pipe(dest);
});
```

Thanks!

**Comment by sofisl** [comment] 2020-07-13 17:13
Hi there! Thanks for filing a bug. Before anything, would you mind installing the latest version of googleapis (npm i googleapis@latest)? I noticed you're on an older version - might be a quick fix!

**Comment by tamj0rd2** [comment] 2020-08-13 11:33
I'm having the same issue with googleapis version 59.0.0

In google drive my file is listed as 20,283 bytes but I only ever receive 16384 bytes. `res.data.on('end')` never seems to get called. Only `res.data.on('finish').

```typescript
public downloadFile = async (fileId: string) => {
  const res = await this.drive?.files.get({ fileId, alt: 'media' }, { responseType: 'stream' })
  if (!res) throw new Error('welp. there was no response apparently?')

  let progress = 0
  const inMemoryStream = new WritableStream()

  await new Promise((resolve, reject) => {
    console.log('starting to download...')
    res.data.on('end', () => {
      console.log(`you'll never see this in the output because it does not get called`)
    })
    res.data.on('finish', () => {
      console.log('finished downloading', progress, 'bytes')
      resolve()
    })
    res.data.on('error', (err) => reject(err))
    res.data.on('data', (data) => {
      progress += data.length
      console.log(`Downloaded ${progress} bytes`)
    })
    res.data.pipe(inMemoryStream)
  })

  return inMemoryStream.toString()
}
```

Output:
```
starting to download...
Downloaded 155 bytes
Downloaded 6353 bytes
Downloaded 13156 bytes
Downloaded 16384 bytes
finished downloading 16384 bytes
SyntaxError: Unexpected end of JSON input
```

The SyntaxError is happening because JSON.parse is failing, due to not having the entire file downloaded.

**Comment by sofisl** [comment] 2020-12-01 23:47
Hi @tamj0rd2,

Unfortunately we weren't able to reproduce the error. I'm curious though, would you mind cloning this repo, and attempting to use the sample (`download.js`) exactly as it stands? I just want to confirm to see if there's a problem with the library or something else.

Thanks!

**Comment by fhinkel** [comment] 2020-12-07 09:58
Hi @sachinsahu731, thank you for the detailed bug report. Unfortunately, this issue tracker has limited visibility and scope - basically, it's just for reporting issues with the samples contained here and is only watched by the folks who work on these samples.

We are happy to help you move this bug to venues where it'll get the attention of the appropriate product teams.

* [StackOverflow's Google Drive API tag](https://stackoverflow.com/questions/tagged/google-drive-api?tab=Newest) is most appropriate for general troubleshooting.
* [Google Drive API's public issue tracker](https://developers.google.com/drive/api/v3/support)

I'm going to close this issue because the folks who own this repo have no actionable way to resolve it directly, but please let us know if there's anything we can do to help!

**Closed by fhinkel** 2020-12-07 09:58 UTC
Labels: api: drive, needs more info, priority: p2, type: bug
