### ISSUE TITLE
Request had insufficient authentication scopes

### ISSUE THREAD

**Issue by wbelk** [googleapis/google-api-nodejs-client#2311] opened 2020-07-30 17:51 UTC
I'm trying to access `google.webmasters('v3')` on behalf of a consenting user. I redirect them to the consent url, then store `refresh_token` and `access_token` from the callback. I'm getting the following error: `Request had insufficient authentication scopes`

I'm sure I'm doing something dumb or omitting an important process step. Can someone point me in the right direction?

My code looks like:

```
const {google} = require('googleapis')
const webmasters = google.webmasters('v3')

const oauth2Client = new google.auth.OAuth2(
  '****',
  '****',
  m.serverAddress + '/google-apis/callback'
)

oauth2Client.credentials = {
    refresh_token: '****',
    access_token: '****'
}
google.options({auth: oauth2Client})

const res = await webmasters.searchanalytics.query({
    siteUrl: 'https://' + domain,
    requestBody: {
      startDate: `${year}-${month}-${day}`,
      endDate: `${year}-${month}-${day}`
    },
    dimensionFilterGroups: [
      {
        groupType: 'and',
        filters: [
          {
            dimension: 'query',
            operator: 'equals',
            expression: unescapedKp
          }
        ]
      }
    ]
  })
```

**Comment by JustinBeckwith** [comment] 2020-07-30 18:47
Greetings!  You need to pass a list of required scopes for the user to accept in your `generateAuthUrl` call:
https://github.com/googleapis/google-api-nodejs-client#generating-an-authentication-url

Please take a look there, and let us know if you have any questions!

**Comment by wbelk** [comment] 2020-07-30 19:22
@JustinBeckwith thank you. I've already passed the scope at the time of the user's consent, I need to generate the consent URL again?

So I would need to `await oauth2Client.getToken(code)` with the `code` I've already stored from the original consent callback, and exchange that code again for a brand new `access_token` before every instantiation of `oauth2Client` each time I want to access the api on behalf of that user?

**Comment by JustinBeckwith** [comment] 2020-07-30 19:46
More or less, yeah.  The first time the user goes through the consent flow, you're going to get both a `refresh_token` and a `access_token` back:
https://github.com/googleapis/google-api-nodejs-client#handling-refresh-tokens

If you want to use the tokens later, you need to securely store the refresh token, and use it when you re-construct your `OAuth2Client` object.  The `setCredentials` method lets you pass in that refresh token, and the library manages fetching a new access token under the hood for you!

**Comment by wbelk** [comment] 2020-07-30 20:16
Ah ok, so then `access_token` only applies to that session/instantiation of `oauth2Client` and is completely temporal? And in effect, I don't need to be concerned with the expiration on `access_token` as it will be refreshed automatically as needed each time I create the `oauth2Client` on behalf of a consented user?

My example use will be that I have a daily process that performs a large handful of requests to `webmasters.searchanalytics.query` for each of many consented users.

**Comment by wbelk** [comment] 2020-07-30 21:15
I've tried three configurations, all generate errors for me. I'm still totally lost as to why I would need to generate an auth url for a user that has already consented and for whom I have already saved the `refresh_token`. I need to access the api in an entirely new future session/instantiation using existing `refresh_token`.

Sorry this is making me feel really dumb and frustrated. What am I missing?

#1 `Error: invalid_grant`:

```
const {google} = require('googleapis')
const webmasters = google.webmasters('v3')

const oauth2Client = new google.auth.OAuth2(
  '***',
  '****',
  m.serverAddress + '/google-apis/callback'
)
const scopes = [
  'https://www.googleapis.com/auth/webmasters.readonly'
]

const url = oauth2Client.generateAuthUrl({
  access_type: 'offline', // 'online' (default) or 'offline' (gets refresh_token)
  scope: scopes
  // prompt: 'consent' use this if need new refresh_token
})

// url does not contain `code`, and user is already consented, so there will be no callback to obtain a new code

const {tokens} = await oauth2Client.getToken( 'SAVED CODE FROM INITIAL CONSENT')

// BREAKS ON LINE ABOVE -- Error: invalid_grant /node_modules/googleapis-common/node_modules/gaxios/build/src/gaxios.js:85:23

oauth2Client.setCredentials(tokens)
```

#2 `Error: Login Required`:

```
const {google} = require('googleapis')
const webmasters = google.webmasters('v3')

const oauth2Client = new google.auth.OAuth2(
  '***',
  '****',
  m.serverAddress + '/google-apis/callback'
)
const scopes = [
  'https://www.googleapis.com/auth/webmasters.readonly'
]

oauth2Client.generateAuthUrl({
  access_type: 'offline', // 'online' (default) or 'offline' (gets refresh_token)
  scope: scopes
  // prompt: 'consent' use this if need new refresh_token
})

oauth2Client.setCredentials({
    refresh_token: 'SAVED REFRESH TOKEN FROM INITIAL CONSENT'
  })

```

#3 `Error: Login Required`

```
const {google} = require('googleapis')
const webmasters = google.webmasters('v3')

const oauth2Client = new google.auth.OAuth2(
  '***',
  '****',
  m.serverAddress + '/google-apis/callback'
)

oauth2Client.setCredentials({
    refresh_token: 'SAVED REFRESH TOKEN FROM INITIAL CONSENT'
  })

```

**Comment by JustinBeckwith** [comment] 2020-07-30 21:22
Oh no! There's a misunderstanding here - in your original code, you didn't show how you set the scopes.  The refresh_token *does* encapsulate the scopes you originally requested.  In example #1, I think the problem is you want to do something like:

```js
const {google} = require('googleapis')
const webmasters = google.webmasters('v3')

const oauth2Client = new google.auth.OAuth2({
  clientId: '*****',
  clientSecret: '******',
  redirectUri: '****',
});
oauth2Client.setCredentials({
  refresh_token: 'SAVED REFRESH TOKEN FROM INITIAL CONSENT'
});
```

That should be enough!  The next call you make through that client should "just work".

**Comment by wbelk** [comment] 2020-07-30 22:01
@JustinBeckwith yes that's the same config as my example number 3 which gives me `Error: Login Required node_modules/googleapis-common/node_modules/gaxios/build/src/gaxios.js:85:23`

**Comment by wbelk** [comment] 2020-07-30 23:13
I also tried `oauth2Client.credentials = {refresh_token: 'SAVED REFRESH TOKEN FROM INITIAL CONSENT'}` with the same error thrown

And I tried using your example where you pass object instead of array for client/redirectUri with same error thrown
```
const oauth2Client = new google.auth.OAuth2({
  clientId: '*****',
  clientSecret: '******',
  redirectUri: '****',
})
```

**Comment by wbelk** [comment] 2020-07-31 15:08
Also another data point, I know that the `refresh_token` works for my test user, I'm using that same token successfully with the Google Ads API package https://www.npmjs.com/package/google-ads-api which requires all the same client credentials and `refresh_token`

**Comment by wbelk** [comment] 2020-08-01 18:39
I am able to successfully query the webmasters endpoint via http requests using the same `refresh_token`

```
const authOptions = {
  uri: 'https://www.googleapis.com/oauth2/v3/token',
  form: {
    grant_type: 'refresh_token',
    client_id: m.googleAuthOptions.client.id,
    client_secret: m.googleAuthOptions.client.secret,
    refresh_token: m.googleAuth[shop].refresh_token
  }
}
request.post(authOptions, (err, data, body) => {
  if (err) return console.log('** err\n', err, '\n\n')
  console.log('AUTH body\n', typeof body, body, '\n\n')
  body = JSON.parse(body)

  const accessToken = body.access_token

  const yesterday = new Date(Date.now() - 86400000)
  const year = yesterday.getFullYear()
  const month = yesterday.getMonth().length === 1 ? `0${yesterday.getMonth()}` : yesterday.getMonth()
  const day = yesterday.getDay().length === 1 ? `0${yesterday.getDay()}` : yesterday.getDay()

  // https://www.googleapis.com/webmasters/v3/sites/siteUrl/searchAnalytics/query

  const siteUrl = 'https://' + m[app].users[shop].shopify_data.domain
  console.log('siteUrl', siteUrl, '\n\n')

  const queryOptions = {
    uri: 'https://www.googleapis.com/webmasters/v3/sites/' + siteUrl + '/searchAnalytics/query',
    headers: {
      Authorization: 'Bearer ' + accessToken,
      'developer-token': 'NzV79j9HAJSlEdWFpr1R7Q'
    },
    form: {
      startDate: `${year}-${month}-${day}`,
      endDate: `${year}-${month}-${day}`,
      dimensionFilterGroups: [
        {
          groupType: 'and',
          filters: [
            {
              dimension: 'query',
              operator: 'equals',
              expression: 'obey'
            }
          ]
        }
      ]
    }
  }
  request.post(queryOptions, (err, data, body) => {
    if (err) return console.log('** err\n', err, '\n\n')
    console.log('QUERY data', data, '\n\n')
    console.log('QUERY body\n', body, '\n\n')
  })
})
```

**Comment by wbelk** [comment] 2020-08-04 18:10
@JustinBeckwith are there any things I can test to try to reduce the problem space here?

**Comment by fhinkel** [comment] 2020-12-07 10:37
Greetings, we're closing this. Looks like the issue got resolved. Please let us know if the issue needs to be reopened.

**Closed by fhinkel** 2020-12-07 10:37 UTC
Labels: needs more info, type: question
