### ISSUE TITLE
How to impersonate a service account?

### ISSUE THREAD

**Issue by kenmorechalfant** [googleapis/google-api-nodejs-client#1962] opened 2020-02-16 17:32 UTC
I authenticate by setting the `GOOGLE_APPLICATION_CREDENTIALS` environment variable to the path to a key for my App Engine service account (e.g. `example@appspot.gserviceaccount.com`).

If a calendar is shared directly to the App Engine service account, I can do just do this:

```
let googleCalendar = google.calendar({
  version: 'v3',
  auth: new google.auth.GoogleAuth({
    scopes: ['https://www.googleapis.com/auth/calendar'],
  })
});

// call Calendar API here
```

But I want users to share their calendar with a different service account I have, `google-calendar@example.iam.gserviceaccount.com`. So I want the App Engine service account to impersonate the `google-calendar` account. I have tried this (and a few other minor variations):

```
let googleCalendar = google.calendar({
  version: 'v3',
  auth: new google.auth.GoogleAuth({
    clientOptions: {
      subject: 'google-calendar@example.iam.gserviceaccount.com'
    },
    scopes: ['https://www.googleapis.com/auth/calendar'],
  })
});
```

I get a 401 error: `Client is unauthorized to retrieve access tokens using this method, or client not authorized for any of the scopes requested.`

I tried making my App Engine service account a Member on the `google-calendar` service account and granting it various Roles  such as `Service Account User` and `Service Account Token Creator` - but nothing changes.

I suspect the code is right and I just don't have the right Roles configured... but at this point I've been searching how to do this for 2 days and I can't find any documentation on exactly how to do this.

**Comment by fhinkel** [comment] 2020-12-07 09:53
Hi @kenmorechalfant , thank you for the detailed bug report. Unfortunately, this issue tracker has limited visibility and scope - basically, it's just for reporting issues with the samples contained here and is only watched by the folks who work on these samples.

We are happy to help you move this bug to venues where it'll get the attention of the appropriate product teams.

* [StackOverflow's Google Calendar tag](https://stackoverflow.com/questions/tagged/google-calendar-api) is most appropriate for design and general troubleshooting.
* [Google Calendar's public issue tracker](https://b.corp.google.com/issues?q=status:open%20componentid:191627%2B%20type:bug) is most appropriate for bugs and unexpected behavior.
* [Google Calendar Support](https://support.google.com/calendar)

I'm going to close this issue because the folks who own this repo have no actionable way to resolve it directly, but please let us know if there's anything we can do to help!

**Closed by fhinkel** 2020-12-07 09:53 UTC
Labels: type: question
