### ISSUE TITLE
Requests hang due to rate limiting and no errors are thrown

### ISSUE THREAD

**Issue by sweetanalytics** [googleapis/google-api-nodejs-client#2495] opened 2020-12-29 16:34 UTC
We are running into a problem where requests to the Analytics module do not resolve and simply hang within the library. No errors are thrown, as we are wrapping calls with try catch. I've created a minimal script to reproduce the issue: 

https://gist.github.com/sweetanalytics/cb9aab1f8a3248044e8edcbfc1101cd3

It may require running the script a few times to hit the rate limiting issue, at which point the script will hang and no errors are thrown.

#### Environment details

  - OS: Ubuntu 18.04.3 LTS and MacOS Catalina
  - Node.js version: v14.15.1
  - npm version: 6.4.1
  - `googleapis` version: 66.0.0

#### Steps to reproduce

  1. Update the variables at the top of the provided script
  2. Run the script

**Comment by sofisl** [comment] 2020-12-29 20:18
Hi @sweetanalytics, can you provide some more information on how you were able to determine that the problem is related to rate limiting if it's just hanging? Unfortunately I can't seem to reproduce this exact situation. 

I also wanted to provide some samples on how to use this service [here](https://github.com/google/google-api-javascript-client/blob/master/samples/analytics/v3/core_reporting_api_v3_reference.js) and [here](https://developers.google.com/analytics/devguides/reporting/core/v3/reference).

**Comment by sweetanalytics** [comment] 2020-12-30 10:12
Hi @sofisl I assumed it was due to rate limiting because the number of errors spike when this is .

![Screen Shot 2020-12-30 at 10 57 56](https://user-images.githubusercontent.com/14118431/103344109-e8b5ba00-4a8d-11eb-9cf7-47ef8efeb492.png)

> Lastly, here's some information on our rates and quota limits: do you think you're hitting these?

We _are_ sending all requests from a single IP on behalf of users. I've just realized of the existence of the `quotaUser` parameter, so let me give that a shot. In any case, the problem seems to be that the API errors are not being thrown, or at least we're not able to catch them. Have you tried running the script that I linked to multiple times and seeing if that triggers the issue?

**Comment by sofisl** [comment] 2020-12-30 21:47
Hi @sweetanalytics,

I wasn't able to get your sample working, so instead I used the sample inside `src`/`apis`/`analytics`/`v3.ts` for this same method, and was able to get it working perfectly. I ran this sample 20 times without having the code hang.

```

const {google} = require('googleapis');
const analytics = google.analytics('v3');
const {authenticate} = require('@google-cloud/local-auth');
const VIEW_ID = "ga:VIEW-ID;

    async function main() {
        const auth = await authenticate({
            keyfilePath:PATH-TO-YOUR-KEYFILE,
            scopes: 'https://www.googleapis.com/auth/analytics',
          });
          google.options({auth});
    
       // Do the magic
       const res = await analytics.data.ga.get({
        ids: [VIEW_ID],
        "start-date": "2020-11-29",
        "end-date": "2020-12-28",
        metrics: "ga:users",
        "start-index": 1,
        samplingLevel: "HIGHER_PRECISION",
        "max-results": 10000,
      });
      console.log(res.data);
    
     main().catch(e => {
       console.error(e);
       throw e;
     });

```

I am not quite sure how your code is different, but I hope this sample works for you. Let me know if you run into any more issues with it!

**Comment by sweetanalytics** [comment] 2020-12-31 12:14
@sofisl I've ran your code and the issue is still happening. The only thing I've changed was the authentication method. Rather than using a keyfile we send requests on behalf of our clients so we use the OAuth2 client for that purpose.

I've also tested adding the `userIp` and `quotaUser` fields to no avail as it still seems to hang after a few attempts.

![Screen Shot 2020-12-31 at 13 08 15](https://user-images.githubusercontent.com/14118431/103409921-45d26e00-4b69-11eb-803b-659c6af83c54.png)

Here's the modified code for reference:

```
const { google } = require("googleapis");
const OAuth2Client = google.auth.OAuth2;

const USER_IP = "XXXXXX"; // <-- this resolves to a real IP
const VIEW_ID = "ga:XXXXXX;
const ACCESS_TOKEN ="XXXXXX";
const REFRESH_TOKEN = "XXXXXX";
const GOOGLE_CLIENT_ID = "XXXXXX";
const GOOGLE_CLIENT_SECRET = "XXXXXX";

async function main() {
  const googleAuth = new OAuth2Client(
    GOOGLE_CLIENT_ID,
    GOOGLE_CLIENT_SECRET,
    "postmessage"
  );

  googleAuth.setCredentials({
    access_token: ACCESS_TOKEN,
    refresh_token: REFRESH_TOKEN,
  });

  const analytics = google.analytics({ version: "v3", auth: googleAuth });

  // Do the magic
  const res = await analytics.data.ga.get({
    ids: [VIEW_ID],
    userIp: USER_IP,
    // quotaUser: "123456789",
    "start-date": "2020-11-29",
    "end-date": "2020-12-28",
    metrics: "ga:users",
    "start-index": 1,
    samplingLevel: "HIGHER_PRECISION",
    "max-results": 10000,
  });
  console.log(res.data.totalsForAllResults);
}

main().catch((e) => {
  console.error(e);
  throw e;
});
```

**Comment by sofisl** [comment] 2021-01-06 00:07
@sweetanalytics, the sample I included above actually uses oAuth2. For `keyFilePath`, you would just use the downloaded JSON for your credentials (`APIs & Services`>`Credentials>`OAuth 2.0 Client IDs` in your console). However, it sounds like your workflow is a little different considering you are working with your users. I'd recommend you look into using an [OAuth2 sample](https://github.com/googleapis/google-auth-library-nodejs/blob/master/samples/oauth2.js), it looks like you might be missing some pieces. 

Just so that we can isolate the issue, can you try the sample I linked above with your personal oAuth credentials (as described above)? If it works, then I think we can safely isolate this issue to authentication!

**Comment by sweetanalytics** [comment] 2021-01-06 13:23
@sofisl thanks for your comments. I've gone ahead and tested using the sample you provided and using the OAuth credentials and interestingly enough, the same issue happens after a few runs.

For each run, it takes me to the browser to authorize access with the usual Google login process, and once authenticated the result of the analytics query is returned. 

![Screen Shot 2021-01-06 at 14 18 44](https://user-images.githubusercontent.com/14118431/103772658-2ab0a400-502a-11eb-963e-7d7947736a55.png)

But after a few attempts it just seems to hang, no errors thrown.

![Screen Shot 2021-01-06 at 14 23 03](https://user-images.githubusercontent.com/14118431/103773010-b296ae00-502a-11eb-9729-2e7923ec05d1.png)

**Comment by sweetanalytics** [comment] 2021-01-06 22:37
So after some additional tests I've realized that it doesn't actually hang indefinitely, it seems to simply take a _really_ long time to resolve the request. I've added some simple timers to check how long it takes to resolve as shown below:

```
  console.time("analyticsQuery");

  const res = await analytics.data.ga.get({
    ids: [VIEW_ID],
    "start-date": "2020-11-29",
    "end-date": "2020-12-28",
    metrics: "ga:users",
    "start-index": 1,
    samplingLevel: "HIGHER_PRECISION",
    "max-results": 10000,
  });
  console.log(res.data.totalsForAllResults);
  console.timeEnd("analyticsQuery")
```

These are the results:

![Screen Shot 2021-01-06 at 23 36 26](https://user-images.githubusercontent.com/14118431/103826915-14c9d000-5078-11eb-9271-d1391c791304.png)

I've run a few times and it looks like the ones that take a long time are taking exactly 4 minutes to finally resolve. Any idea as to what could be causing this behaviour?

**Comment by sofisl** [comment] 2021-01-06 22:48
@sweetanalytics, thanks for giving this a second attempt! I'm attempting to reproduce but unfortunately I can't seem to get it to hang, despite attempting multiple times in a row (10+ times). 

@JustinBeckwith or @bcoe, do you have any thoughts on investigating further? Is this at all a known issue?

**Comment by sweetanalytics** [comment] 2021-01-07 02:32
@sofisl no problem, it's definitely a strange issue, and it definitely seems to be account specific if the only difference between our code is the key file and the view ID, and it's not happening to you.

I've gone further and created a new project in the GCP (with new OAuth key and everything) to see if that had any impact, but it doesn't seem to have helped. Unfortunately I'm still seeing the exact same behavior, it resolves exactly at the 4 min mark.

**Comment by tylermichael** [comment] 2021-01-11 16:57
FWIW, I'm also getting this issue in my project. My process has ran fine for about two years with no issues, then started to hang like this on December 13th 2020. Then it started to work fine for about a week and then on January 9, it started to show the same issues again.

**Comment by sweetanalytics** [comment] 2021-01-11 17:01
@tylermichael thanks for your feedback. I think it was about the same time when it started happening to us as well.

**Comment by sweetanalytics** [comment] 2021-01-18 22:27
@sofisl I wanted to wait a few days before confirming, but the issue seems to have resolved itself. I wanted to be absolutely sure, but no timeouts are occurring anymore! I assume somebody from the Google team has something to do with it suddenly working again, so thanks to everyone that helped out!

@tylermichael can you confirm it's also working for you?

**Comment by tylermichael** [comment] 2021-01-19 15:48
The last time I had an issue was on January 11th when I commented. I ended up putting a sleep in between iterations in my for loop to try and avoid this issue, which seemed to help.

**Comment by bcoe** [comment] 2021-01-27 01:42
> but no timeouts are occurring anymore! 

@sweetanalytics  that's great news that this is working for you again 👍  It sounds to me like it might have ultimately been a problem with the API itself, which perhaps resolved.

Closing for now, please don't hesitate to open the issue if the problem starts happening regularly again.

**Closed by bcoe** 2021-01-27 01:42 UTC
Labels: priority: p2, type: bug
