### ISSUE TITLE
Error: Invalid conference type value.

### ISSUE THREAD

**Issue by marytal** [googleapis/google-api-nodejs-client#3234] opened 2023-05-11 14:49 UTC
#### Environment details

  - OS: 
  - Node.js version: v16.14.2
  - npm version: 8.5.0
  - `googleapis` version: @googleapis/calendar ^6.0.0

#### Steps to reproduce

1. Create a service account, grant it access to the Google Calendar API
2. Create key/value pair & download credentials
3. Create a calendar on your service account with `calendar.insert`
4. Use the calendar ID you created, as well as the correct keyFile path in this code:

```typescript
import { calendar, auth } from "@googleapis/calendar";

const googleAuth = new auth.GoogleAuth({
  scopes: [
    "https://www.googleapis.com/auth/calendar",
    "https://www.googleapis.com/auth/calendar.events",
  ],
  keyFile: "./src/integrations/google/credentials.json",
});

export const createEvent = async () => {
  const body = {
    summary: "New Event!",
    description: "My new event",
    end: {
      date: "2023-05-11",
    },
    start: {
      date: "2023-05-11",
    },
    conferenceData: {
      createRequest: {
        conferenceSolutionKey: {
          type: "hangoutsMeet",
        },
        requestId: "12345678",
      },
      entryPoints: [
        {
          entryPointType: "video",
        },
      ],
    },
  };
```
5. Run the code

Error:
```
Error: Invalid conference type value.
    at Gaxios._request (/Users/marybriskin/Desktop/tbt-portal/graphql/node_modules/gaxios/src/gaxios.ts:158:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at JWT.requestAsync (/Users/marybriskin/Desktop/tbt-portal/graphql/node_modules/google-auth-library/build/src/auth/oauth2client.js:382:18)
    at createEvent (/Users/marybriskin/Desktop/tbt-portal/graphql/src/integrations/google/index.ts:58:15)
```
(note, the issue only occurs if you attempt to pass a `createRequest` to the event creation)

**Comment by marytal** [comment] 2023-05-11 19:03
Looks like I had to switch to using a JWT token and adding a subject (to impersonate the user, because I guess service accounts can't create conferences?)

```TypeScript
const googleAuth = new auth.JWT({
  email: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,
  key: process.env.GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY,
  scopes: ["https://www.googleapis.com/auth/calendar"],
  subject: "subject@email.come",
});

```

Is there a way to improve that error message?

**Comment by sofisl** [comment] 2023-05-25 19:26
Hi @marytal, seems like this is a duplicate of: https://github.com/googleapis/google-api-nodejs-client/issues/3052, https://github.com/googleapis/google-api-nodejs-client/issues/3197.

You need to enable domain-wide delegation to use a SA, otherwise you can use a JWT error message. I have sent over a request to update documentation!

**Closed by sofisl** 2023-05-25 19:26 UTC
Labels: type: bug, priority: p2

**Comment by MOIN-AKHTAR** [comment] 2023-07-04 07:18
I want to create a google meet link for a google calander event.For that i have create a service-account.json and also enabled calander api for my project and given access of my personal google account calander to email of this service-account.json.Now when i am trying to create a google calander and config calander event in such a way that it should create google meet link i am getting error Invalid conference type value but if i not configiguring google meet link thing than event is being created successfully.Kindly guide me what i am doing wrong.
My whole code is here:
https://github.com/MOIN-AKHTAR/calmder_event_via_service_account
Kindly plz help me i need to done this asap.

**Comment by EliasTouil** [comment] 2023-08-16 21:42
+1 Same problem as @MOIN-AKHTAR

**Comment by akshaychopra5207** [comment] 2024-01-18 08:05
somebody has reference how to do this in python. I cannot enable domain wide delegation and I am using service account How to create jwt in python and use with calender api

**Comment by akshaychopra5207** [comment] 2024-01-19 15:48
@sofisl @marytal 
So service account cannot create the google meet invite in their own calender without domain wide delegation?
Is there any alternative of not enabling domain wide delegation. I just need to create meeting link which everybody can join by clicking that link. I am doing this in python but I think the basics are the same for all

**Comment by jstcode99** [comment] 2024-03-21 02:15
@akshaychopra5207 @marytal did you could fix it? I have same error with this. lmao calendar

**Comment by akshaychopra5207** [comment] 2024-03-23 20:26
You need to enable domain wide delegation and impersonate an actual google user to create google meet @jstcode99

**Comment by jstcode99** [comment] 2024-03-26 17:02
@akshaychopra5207 Bro, do you have time for quick meet to help me on process of configuration?

**Comment by jstcode99** [comment] 2024-04-01 15:36
@marytal 

it's my config but always it's return with 400 or Invalid conference type value or account delegation but I think that I have all ok on my config and code
![Screenshot from 2024-04-01 10-34-28](https://github.com/googleapis/google-api-nodejs-client/assets/90060291/3bc09956-6f9e-4f17-a1d2-0d7b9a3718f3)
![Screenshot from 2024-04-01 10-34-02](https://github.com/googleapis/google-api-nodejs-client/assets/90060291/16aecce1-a562-4cf5-ba52-686f9c156fde)
![Screenshot from 2024-04-01 10-33-44](https://github.com/googleapis/google-api-nodejs-client/assets/90060291/2e27fce0-223a-443b-9db1-222c10b80b15)

`
<?php

namespace App\Repositories;

use App\Contracts\Calendar\CalendarRepositoryContract;
use Carbon\Carbon;
use Google\Client;
use Google_Service_Calendar;
use Google_Service_Calendar_Event;
use Illuminate\Support\Collection;

class CalendarRepository implements CalendarRepositoryContract
{
    private string $path;
    private string $calendarId;
    private Client $client;


    public function __construct()
    {
        $this->path = storage_path(\config('calendar.credentials_path'));

        $this->calendarId = \config('calendar.id');

        putenv('GOOGLE_APPLICATION_CREDENTIALS=' . $this->path);

        $this->client = new Client();

        $this->client->useApplicationDefaultCredentials();
        $this->client->setSubject(\config('calendar.impersonate_email'));

        $this->client->addScope([
            Google_Service_Calendar::CALENDAR_EVENTS,
            Google_Service_Calendar::CALENDAR
        ]);
    }

    /**
     * Generate New Google Calendar Event + related Google Meet Link
     *
     * @return string Google Meet Link of the scheduled event
     */

    public function createMeet(): string
    {

        // Set up the Calendar API service
        $service = new Google_Service_Calendar(
            clientOrConfig: $this->client
        );

        // Create a new event on Google Calendar
        $event = new Google_Service_Calendar_Event(
            [
                'summary'        => 'Meeting ' . Carbon::now(),
                'location' => '800 Howard St., San Francisco, CA 94103',
                'description' => 'A chance to hear more about Google\'s developer products.',
                'start'          => [
                    'dateTime' => Carbon::now(),
                    'timeZone' => 'America/Bogota',
                ],
                'recurrence' => [
                    'RRULE:FREQ=DAILY;COUNT=2'
                ],
                // 'attendees' => array(
                //     array('email' => 'jstorres0211@gmail.com'),
                // ),
                'end'            => [
                    'dateTime' => Carbon::now()->addHour(),
                    'timeZone' => 'America/Bogota',
                ],
                // Payload section needed to create a unique Google Meet link for the appointment
                'conferenceData' => [
                    'createRequest' => [
                        'requestId'             => uniqid(),
                        'conferenceSolutionKey' => [
                            'type' => 'hangoutsMeet'
                        ]
                    ],
                    'entryPoints' => [
                        [
                            'entryPointType' => "video",
                        ],
                    ],
                ],
            ]
        );

        // Insert the event into the targeted Google Calendar
        $event = $service->events->insert(
            calendarId: $this->calendarId,
            postBody: $event,
            optParams: ['conferenceDataVersion' => 1] // To allow for Google Meet Link creation
        );

        dd($event);

        $link = $event->getHangoutLink();

        dd($link);
        // Retrieve the generated Google Meet link from the event's conference data
        return $event->getHangoutLink();
    }

    public function getMeets(): Collection
    {


        $service = new Google_Service_Calendar($this->client);

        $optParams = array(
            'maxResults' => 10,
            'orderBy' => 'startTime',
            'singleEvents' => true,
            // 'timeMin' => date('c', strtotime('2023-01-01 00:00am -1 minute')),
            // 'timeMax' => date('c', strtotime('2022-04-20 10:00pm +1 minute')),
        );

        $results = $service->events->listEvents($this->calendarId, $optParams);
        $events = collect([]);
        foreach ($results->getItems() as $event) {
            $events->add([
                'meet' => $event?->hangoutLink,
                'summary' => $event->summary,
                'status' => $event->status,
                'start' => $event->start->dateTime,
                'end' => $event->end->dateTime,
            ]);
        }

        return $events;
    }
}

`

**Comment by rezafarzaneh7** [comment] 2024-04-28 18:53
is there any update here ? did you solve meet link creation problem ?

**Comment by hackpiy1** [comment] 2024-06-19 13:35
Yes guys there's an update.

For you to programatically create meetings using GOOGLE MEET REST API or GOOGLE CALENDAR API, you must have a google workspace account.
To have a google workspace account, you must be willing to pay at least $13 per user monthly.

I think this modification was made some few weeks ago when they launched GOOGLE MEET REST API.

**Comment by anatoliy-t7** [comment] 2025-12-25 11:31
it works only with JWT
