### ISSUE TITLE
Drive class is not listed for drive V3 api

### ISSUE THREAD

**Issue by ghost** [googleapis/google-api-nodejs-client#1689] opened 2019-05-02 13:13 UTC
- API V39.2.0
- Using typescript 3.4.5
- Node.js 11

Hi,
I'm trying to get the list of drives using the V3 of google.drive.
But the drives resources if not listed in the Drive class, although I can see it in the V3.ts file....

Any help ?

![drivesmissing](https://user-images.githubusercontent.com/37058666/57077626-cda90a80-6cec-11e9-992d-110b532ef67f.png)

Here the `drives` is not available.
```
const driveList = google.drive({ version: "v3", auth });
  const AllDrives = await driveList.drives.list({
        pageToken,
        maxResults : 
      })

```

**V3.ts definition :**
```
export class Drive {
    context: APIRequestContext;
    about: Resource$About;
    changes: Resource$Changes;
    channels: Resource$Channels;
    comments: Resource$Comments;
    drives: Resource$Drives;
    files: Resource$Files;
    permissions: Resource$Permissions;
    replies: Resource$Replies;
    revisions: Resource$Revisions;
    teamdrives: Resource$Teamdrives;
```

**Comment by jejesh26** [comment] 2019-05-03 08:24
any help ?

**Comment by imjustd** [comment] 2019-05-14 07:10
Any update for this? Still using the deprecated `teamdrives` API instead of the new `drives` API.

**Comment by bcoe** [comment] 2019-05-14 20:15
@imjustd @ghost, we regenerated and published a newer version of the APIs yesterday, so it might be worth testing version `40`, and seeing if this issue is still cropping up.

If the issue is cropping up, we'll try to dig into this bug as soon as possible :+1:  thanks for reporting.

**Comment by imjustd** [comment] 2019-05-16 11:09
I can confirm it works, although it is still required to use deprecated parameters like `includeItemsFromAllDrives` and `supportsAllDrives` in order to work, although in the docs for `files.list()` it clearly says they are deprecated https://developers.google.com/drive/api/v3/reference/files/list

**Comment by JustinBeckwith** [comment] 2019-05-16 16:47
Awesome!  For the need to use deprecated parameters - for that would you mind filing a new bug here?
https://developers.google.com/drive/api/v3/support

There's not a lot we can do with the backend support, so I'm going to close this out.  Thank you!

**Closed by JustinBeckwith** 2019-05-16 16:47 UTC
Labels: needs work, priority: p2, type: question
