### ISSUE TITLE
npm install => Cannot find type definition file for 'node'.

### ISSUE THREAD

**Issue by micktaiwan** [googleapis/google-api-nodejs-client#2411] opened 2020-10-23 09:12 UTC
Just following the steps from
https://github.com/googleapis/google-api-nodejs-client/tree/master/src/apis/calendar
for building a browser bundle

clone the repo => ok
then
$ cd src/apis/calendar
$ npm install

I get this error :

> @google/calendar@0.1.0 prepare /home/mick/projects/google-api-nodejs-client/src/apis/calendar
> npm run compile

> @google/calendar@0.1.0 compile /home/mick/projects/google-api-nodejs-client/src/apis/calendar
> tsc -p .

> node_modules/gaxios/build/src/common.d.ts:1:23 - error TS2688: Cannot find type definition file for 'node'.

> 1 /// <reference types="node" />

**Comment by sofisl** [comment] 2020-10-26 21:47
Hi there, 

Is this issue still persisting? Can you confirm that you have the latest version? Afterwards, I would just recommend clearing out node_modules and then re-installing.

**Comment by micktaiwan** [comment] 2020-10-26 21:56
I have removed the node_modules folder, but the error persists when running "npm install" inside the src/apis/calendar/ folder

**Comment by sofisl** [comment] 2020-10-26 21:58
Hmm, I'm not able to reproduce the issue. Have you tried running `npm i` on the top-level folder as well? Can you also confirm you are on the latest version of this library? Thanks!

**Comment by sofisl** [comment] 2020-12-10 17:46
Closing this as we upgraded recently to webpack 5.

**Closed by sofisl** 2020-12-10 17:46 UTC
Labels: priority: p2, type: bug
