### ISSUE TITLE
Cannot find module './docs'

### ISSUE THREAD

**Issue by kilianc** [googleapis/google-api-nodejs-client#1675] opened 2019-04-18 00:09 UTC
#### Environment details

  - OS: macOS
  - Node.js version: 10 and 11
  - npm version: n/a (yarn)
  - `googleapis` version:  39.2.0

#### Steps to reproduce

  1. `yarn add --exact googleapis`
  2. `const { google } = require('googleapis')`

```
Error: Cannot find module './docs'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/.../node_modules/googleapis/build/src/apis/index.js:77:14)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)```

**Comment by corbfon** [comment] 2019-04-27 19:43
Seconded. Node version `v10.15.0`, `googleapis` version `39.2.0`

```javascript
const { google } = require('googleapis')
const people = google.people('v1')
```

The error is thrown on build. If you comment out the second line, where we get the `people` api, the build error goes away. Also tried installing `googleapis` version `38.0.0` and still got the error.

**Comment by corbfon** [comment] 2019-04-27 21:44
Looks like pinning `"googleapis": "37.0.0"` will solve this issue, as long as you don't depend on the changes from the last couple of versions.

**Comment by bcoe** [comment] 2019-05-06 03:40
@kilianc did `37.0.0` unblock you?

**Comment by aDEVE** [comment] 2019-05-20 16:22
`"googleapis": "37.0.0"` work for me

**Comment by JustinBeckwith** [comment] 2019-05-20 16:40
I'm going to close this out for now.  Please do let us know if you're still having problems!

**Comment by aDEVE** [comment] 2019-05-22 14:49
I upgrade on version `"googleapis": "^40.0.0"` and i have still the same error 🤔 
I downgrade `"googleapis": "37.0.0"` to do my job

**Comment by bcoe** [comment] 2019-05-22 20:24
@aDEVE would you be able to provide a GitHub repository with a minimum reproduction of this bug?

**Comment by JustinBeckwith** [comment] 2019-05-22 21:43
Weird, I'm unable to reproduce this.  Very specific steps for me, running OSX:

```
$ node -v
v11.15.0

$ yarn -v
1.16.0

$ yarn add --exact googleapis
yarn add v1.16.0
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Saved 1 new dependency.
info Direct dependencies
└─ googleapis@40.0.0
info All dependencies
└─ googleapis@40.0.0
✨  Done in 0.47s.

$ cat server.js 
const {google} = require('googleapis');
const people = google.people('v1')
console.log(people);

$ yarn start
yarn run v1.16.0
$ node server.js
People {
  context:
   { _options: {},
...
```


Can you share:
- What version of nodejs are you running? 
- What version of yarn?
- Are you using electron?
- Are you using webpack?
- Are you using create-react-app?

**Comment by s4tori** [comment] 2019-05-29 14:19
This bug is relative to the `.yarnclean` file. This file is provided by Yarn to automatically remove useless files inside *node_modules* directory. By default, `yarn autoclean --init` generates a `.yarnclean` file that exclude `docs` directories:

```yml
# asset directories
docs
doc
website
images
assets
```

To reproduce the problem: 

```bash
yarn init --yes
yarn install
yarn autoclean --init
yarn add googleapis 

node -e 'require("googleapis");'
# > Cannot find module './docs'
```

A very simple solution is to add an exception inside the `.yarnclean` file **before** installing googleapis package:

```bash
# asset directories
docs
!googleapis/build/src/apis/docs
```

But, without this change, `yarn autoclean --init` isn't compatible with googleapis...
The `docs` directory has been added in [v37.2.0](https://github.com/googleapis/google-api-nodejs-client/releases/tag/v37.1.0). So, this error only appears after `v37.0.0`.

**Comment by romain-n** [comment] 2019-05-29 14:19
This bug is relative to the `.yarnclean` file. This file is provided by Yarn to automatically remove useless files inside *node_modules* directory. By default, `yarn autoclean --init` generates a `.yarnclean` file that exclude `docs` directories:

```yml
# asset directories
docs
doc
website
images
assets
```

To reproduce the problem: 

```bash
yarn init --yes
yarn install
yarn autoclean --init
yarn add googleapis 

node -e 'require("googleapis");'
# > Cannot find module './docs'
```

A very simple solution is to add an exception inside the `.yarnclean` file **before** installing googleapis package:

```bash
# asset directories
docs
!googleapis/build/src/apis/docs
```

But, without this change, `yarn autoclean --init` isn't compatible with googleapis...
The `docs` directory has been added in [v37.2.0](https://github.com/googleapis/google-api-nodejs-client/releases/tag/v37.1.0). So, this error only appears after `v37.0.0`.

**Comment by JustinBeckwith** [comment] 2019-06-10 15:26
Unless others have an idea of how to reasonably fix this on our side, I sadly think I need to close this out.  The name `docs` and the accompanying directory is pretty key to the `Google Docs` product, and not something I think we can easily change.  If others can think of something we could do - I would be more than happy to help!

I find it a little alarming that `yarn` would set a default like this that's potentially destructive.  @bcoe you know anyone over on that side of the world?

**Closed by JustinBeckwith** 2019-06-10 15:26 UTC
Labels: needs more info, priority: p2, type: bug

**Comment by Sleepful** [comment] 2021-09-10 22:37
using https://github.com/tj/node-prune causes the same error, fix was to remove node-prune.

**Comment by ben-pr-p** [comment] 2025-03-17 17:43
I'm running into this issue with Bun - if anyone has any ideas for how to fix it, let me know
